spring.application.name=pop-cart-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test


project.images.path=images/

spring.app.jwtSecret=mySecretKey12303152026qewrtryjhsaAGFGYETWQEERSGHGFJdsfgjhdfhfghxvdbxcvnxfghxfdhgxdfgxfdgxfdg
spring.app.jwtExpirationMs=86400000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.popcartecom=DEBUG