spring.application.name=pop-cart-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test


project.images.path=images/

spring.app.jwtSecret=mySecretKey123!#03152026
spring.app.jwtExpirationMs=86400000